-- CUSTOMER TABLE
CREATE TABLE CUSTOMER(
    cust_ID INT PRIMARY KEY,
    FNAME VARCHAR(255) NOT NULL,
    LNAME VARCHAR(255) NOT NULL,
    GENDER VARCHAR(2) NOT NULL,
    AGE NUMBER(3) NOT NULL,
    CUST_CONTACT_NUM NUMBER(11) NOT NULL,
    cust_email VARCHAR(255) NOT NULL,
    cust_password VARCHAR(20) NOT NULL
);

---------
-- CREATING SEQUENCE TO AUTO INCREMENT CUSTOMER ID
---------
CREATE SEQUENCE CUSTOMER_SEQ
START WITH 1001
INCREMENT BY 1
CACHE 10
NOMAXVALUE;

SELECT * FROM CUSTOMER;

-----------
-- INSERTING DATA INTO TABLE
-----------
INSERT INTO CUSTOMER(CUSTOMER_SEQ.nextval,'Sri','K','F',21,3647829183,'sri@gmail.com','sri123');

DROP TABLE CUSTOMER;
