-- ADMIN TABLE
CREATE TABLE ADMIN(
    ADMIN_ID INT PRIMARY KEY,
    FNAME VARCHAR(255) NOT NULL,
    LNAME VARCHAR(255) NOT NULL,
    GENDER VARCHAR(2) NOT NULL,
    AGE NUMBER(3) NOT NULL,
    ADMIN_CONTACT_NUM NUMBER(11) NOT NULL,
    ADMIN_EMAIL VARCHAR(255) NOT NULL,
    ADMIN_PASSWORD VARCHAR(255) NOT NULL
);

SELECT * FROM ADMIN;

------
-- Insert into admin table
------
INSERT INTO ADMIN VALUES(101, 'ABHINAV', 'ADITYA', 'M', 25, 7079020419, 'abhinav@gmail.com', 'abhinav123');

UPDATE ADMIN SET ADMIN_ID = 101 WHERE ADMIN_ID = 1;

DELETE FROM ADMIN WHERE ADMIN_ID = 101;

-- DROP TABLE ADMIN;
DROP TABLE ADMIN;