-- Airport Details Table
CREATE TABLE AIRPORT_DETAILS(
    ARP_CODE VARCHAR(4) PRIMARY KEY,
    ARP_NAME VARCHAR(50) NOT NULL
)

---------
-- INSERT AIRPORT DETAILS
---------
INSERT INTO AIRPORT_DETAILS VALUES('DEL', 'DELHI AIRPORT');
INSERT INTO AIRPORT_DETAILS VALUES('BOM', 'BOMBAY AIRPORT');
INSERT INTO AIRPORT_DETAILS VALUES('BLR', 'BANGALORE AIRPORT');
INSERT INTO AIRPORT_DETAILS VALUES('HYD', 'HYDERABAD AIRPORT');
INSERT INTO AIRPORT_DETAILS VALUES('GOA', 'GOA AIRPORT');
INSERT INTO AIRPORT_DETAILS VALUES('CCU', 'KOLKATA AIRPORT');
INSERT INTO AIRPORT_DETAILS VALUES('PNQ', 'PUNE AIRPORT');
INSERT INTO AIRPORT_DETAILS VALUES('MAA', 'CHENNAI AIRPORT');

DROP TABLE AIRPORT_DETAILS;

---------
-- Show AIRPORT DETAILS
---------
SELECT * FROM AIRPORT_DETAILS;