-- AIRPLANE DETAILS
CREATE TABLE AIRPLANE_DETAILS(
    AIRPLANE_ID VARCHAR(3) PRIMARY KEY,
    AIRPLANE_NAME VARCHAR(50) NOT NULL
);

DROP TABLE AIRPLANE_DETAILS;
---------
-- INSERT AIRPLANE DETAILS
---------
INSERT INTO AIRPLANE_DETAILS VALUES('A01', 'AIRBUS A320');
INSERT INTO AIRPLANE_DETAILS VALUES('A02', 'AIRBUS A330');
INSERT INTO AIRPLANE_DETAILS VALUES('A03', 'AIRBUS A340');
INSERT INTO AIRPLANE_DETAILS VALUES('A04', 'AIRBUS A350');
INSERT INTO AIRPLANE_DETAILS VALUES('A05', 'AIRBUS A380');
INSERT INTO AIRPLANE_DETAILS VALUES('B01', 'BOEING 737');
INSERT INTO AIRPLANE_DETAILS VALUES('B02', 'BOEING 747');


---------
-- SHOW ALL AIRPLANE DETAILS
---------
SELECT * FROM AIRPLANE_DETAILS;


