-- Flight Schedule
CREATE TABLE FLIGHT_SCHEDULE(
    SCHED_ID VARCHAR(3) PRIMARY KEY,
    AIRPLANE_ID VARCHAR(3) NOT NULL,
    SCHED_DATE DATE NOT NULL,
    DEPART_TIME VARCHAR(10) NOT NULL,
    SRC_AIRPORT_CODE VARCHAR(4) NOT NULL,
    DEST_AIRPORT_CODE VARCHAR(4) NOT NULL,
    CONSTRAINT FK_AIRPLANE FOREIGN KEY (AIRPLANE_ID) REFERENCES AIRPLANE_DETAILS(AIRPLANE_ID)
    ON DELETE CASCADE,
    CONSTRAINT FK_SRC_AIRPORT FOREIGN KEY (SRC_AIRPORT_CODE) REFERENCES AIRPORT_DETAILS(ARP_CODE)
    ON DELETE CASCADE,
    CONSTRAINT FK_DEST_AIRPORT FOREIGN KEY (DEST_AIRPORT_CODE) REFERENCES AIRPORT_DETAILS(ARP_CODE)
);

-------------
-- INSERT SCHEDULE
-------------
INSERT INTO FLIGHT_SCHEDULE VALUES('S01', 'A01', '01-JAN-2023', '10:00', 'BOM', 'DEL');

-------------
-- DELETE SCHEDULE
-------------
DELETE FROM FLIGHT_SCHEDULE WHERE SCHED_ID = 'SH1';

-------------
-- SHOW FLIGHT SCHEDULES
-------------
SELECT * FROM FLIGHT_SCHEDULE;


DROP TABLE FLIGHT_SCHEDULE;