-- Ticket Table
CREATE TABLE TICKET(
    TICKET_ID INT PRIMARY KEY,
    DATE_AVAILED DATE NOT NULL,
    DATE_FLIGHT DATE NOT NULL,
    TIME_DEPART VARCHAR(10) NOT NULL,
    SOURCE VARCHAR(50) NOT NULL,
    DESTINATION VARCHAR2(50) NOT NULL
);

SELECT * FROM TICKET;
DROP TABLE TICKET;

--------
-- INSERT INTO TICKET TABLE
--------
INSERT INTO TICKET VALUES(1, '01-DEC-2022', '01-JAN-2023', '10:00', 'BOM', 'DEL');

DELETE FROM TICKET WHERE TICKET_ID = 100001;