-- RESERVATION TABLE
CREATE TABLE RESERVATION(
    RES_ID  INT PRIMARY KEY,
    ADMIN_ID INT NOT NULL,
    CUST_ID INT NOT NULL,
    TICKET_ID INT NOT NULL,
    DATE_RESERVE DATE NOT NULL,
    DATE_ACCOM DATE NOT NULL,
    CONSTRAINT FK_RES_ADMIN FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN(ADMIN_ID),
    CONSTRAINT FK_RES_CUST FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID),
    CONSTRAINT FK_RES_TICKET FOREIGN KEY (TICKET_ID) REFERENCES TICKET(TICKET_ID)
);

SELECT * FROM RESERVATION;

-----------
-- CREATE SEQUENCE TO AUTO INCREMENT RESERVATION ID
-----------
CREATE SEQUENCE RESERVATION_SEQ
START WITH 1
INCREMENT BY 1
CACHE 10
NOMAXVALUE;

---------
-- INSERT INTO RESREVATION TABLE
---------
INSERT INTO RESERVATION(RESERVATION_SEQ.nextval, 101, 1, 1,'01-JAN-2023', '01-DEC-2022');

DELETE FROM RESERVATION WHERE RES_ID = 1;
DROP TABLE RESERVATION;

