-------------------------------------------------------------------------
-- TRANSACTION TABLE
-------------------------------------------------------------------------
CREATE TABLE TRANSACTION(
    TRANS_ID INT PRIMARY KEY,
    ADMIN_ID NUMBER(11) NOT NULL,
    SCHED_ID INT NOT NULL,
    RES_ID NUMBER(11) NOT NULL,
    CUST_ID NUMBER(11) NOT NULL,
    TRANS_DATE DATE NOT NULL,
    CONSTRAINT FK_ADMIN FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN(ADMIN_ID),
    CONSTRAINT FK_SCHED FOREIGN KEY (SCHED_ID) REFERENCES FLIGHT_SCHEDULE(SCHED_ID),
    CONSTRAINT FK_RES FOREIGN KEY (RES_ID) REFERENCES RESERVATION(RES_ID)
);

---------
-- CREATE SEQUENCE FOR TRANS_ID
---------
CREATE SEQUENCE TRANSACTION_SEQ
START WITH 12131
INCREMENT BY 1
CACHE 10
NOMAXVALUE;

-------
-- INSERT INTO TRANSACTION TABLE
-------
INSERT INTO TRANSACTION VALUES(TRANSACTION_SEQ.nextval, 101, 1001, 3, 1002, '01-DEC-2022');

---------
-- SHOW TRANSACTION TABLE
---------
SELECT * FROM TRANSACTION;

-------
-- Drop Table
-------
DROP TABLE TRANSACTION;

